config/routes.rb
Rails.application.routes.draw do
 

  
    
                    root "static_pages#home"
                    get  "/users/new" => "users#new",as: :user_new 
                    post "/users/new"=> "users#create"
                    get "/users"=> "users#index",as: :new_list
                    get "/users/:id/edit" => "users#edit",as: :edit_new

                    get "/login"=> "sessions#new",as: :new_login
  
                    post "/login"=> "sessions#create"
                    delete "/logout"=>"sessions#destroy",as: :new_logout

                    get "/actions/new"=>"actions#new",as: :action_new
                    post "/actions"=>"actions#create",as: :action_create
                    get "/actions"=>"actions#index",as: :action_index
                     get "/actions/:id"=>"actions#show",as: :action_show
                     get  "/actions/:id/edit"=>"actions#edit", as: :action_edit 
                     put "/actions/:id/update"=>"actions#update",as: :action_update      
                    

                

end

app/models/action.rb
class Action < ActiveRecord::Base
	belongs_to :owner,class_name: "User"
	has_many :participants
	has_many :users,through: :participants
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :user
  belongs_to :action
end

app/models/user.rb
class User < ActiveRecord::Base

 has_many :actions,foreign_key: :owner_id
	has_secure_password
	def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
def show

  @action=Action.find_by_id(params[:id])
end

 def index
   @actions=Action.all
   @user=User.all
 end


 def new
  
   @action = Action.new
 end

 def create

   @action = Action.new(action_params)
   @action.owner = current_user
   @action.users << User.find(params["participant"])
   if @action.save
     flash[:success] = "action created!"
     redirect_to action_index_path
   else
     render :new
   end
 end
 def edit

   @action=Action.find_by_id(params[:id])
 end

 def update
   
   @action=Action.find_by_id(params[:id])
   @action.update_attributes(action_params)
 end

 def destroy
   @action.destroy
   flash[:success] = "action deleted"
   redirect_to request.referrer || root_url
 end

 private
    def action_params
      
      params.require(:event_action).permit(:event_title, :venue, :date, :time, :description, :status)
    end

    def find_user
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include FlashHelper
  def current_user

    @current_user ||= User.find(session[:user_id]) if session[:user_id]
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new

 end
# end
#   def create
#   @user = User.authenticate(params[:email], params[:password])
#   if @user
#     session[:user_id] = @user.id
#     redirect_to root_url, :notice => "Logged in!"
#   else
#     flash.now.alert = "Invalid email or password"
#     render "new"
#   end
# end

# def destroy
#   session[:user_id] = nil
#   redirect_to root_url, :notice => "Logged out!"
# end



def create

  @user = User.find_by_email(params[:session][:email])
  if @user && @user.authenticate(params[:session][:password])


   session[:user_id]=@user.id
   store_flash_message("logged in succesfully", :success)
   redirect_to action_index_path
 else
  store_flash_message("Invalid email or password", :error)
  redirect_to root_path
end

end

def destroy
 session[:user_id]=nil
 flash[:success]="Loggedout"
 redirect_to root_path
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user=User.all
		
	end
	def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
     @user.save
     
     redirect_to new_login_path
 
    end
  

  private

    def user_params
      params.require(:user).permit(:first_name,:last_name,:email,:phone_number,:username, :password,
                                   :password_confirmation)
    end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper

 # This function will set a flash message depending up on the request type (ajax - xml http or direct http)
 # example : store_flash_message("The message has been sent successfully", :success)
 # FIXME - example, documention & spec # No need for documentation
 def store_flash_message(message, type)
   if request.xhr?
     flash.now[type] = message
   else
     flash[type] = message
   end
 end

end

app/helpers/gif_helper.rb
module GifHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
    if (user_id = session[:user_id])
      @current_user = User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
 end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actions/_form.html.erb
<div class="modal-dialog">

  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"></h4>
    </div>
    <div class="modal-body">
      <div class="row">
       <div class="col-md-6 col-md-offset-3">
       <%= form_for :event_action, url: action_create_path  do |f| %>
         <%= f.label :event_title  %>
         <%= f.text_field :event_title,required: true %><br><br>

         <%= f.label :venue%>
         <%= f.text_field :venue,required: true %><br><br>

         <%= f.label :date %>
         <%= f.text_field :date,required: true %><br><br>

         <%= f.label :time%>
         <%= f.text_field :time,required: true %><br><br>
         <%= f.label :description %>
         <%= f.text_area :description,:required=> true %><br><br>



         <%= f.fields_for :participants do |e|%>
         <% User.all.each do |d|%>
         <%= check_box_tag "participant[]", d.id%>
         <%= d.first_name %><br>

         <% end %>
         <% end %>
         <%=f.submit%>
         <% end %>
       


       </div>
     </div>
   </div>
   <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">open</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
</div>

</div>

app/views/actions/edit.html.erb
<div class="container">
<% if current_user.id==@action.id%>
<center><h1>Edit action</h1></center><div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="well">
 <%= form_for :event_action, url:action_update_path,method: :put do |f| %>
       <%= f.label :Title %>
   <%= f.text_field :event_title, class: "form-control" %>          <%= f.label :Venu %>
   <%= f.text_field :venue, class: "form-control" %>      <%= f.label :Description %>
   <%= f.text_area :description, size: "10x3", class: "form-control" %>
   <%= f.label :Invitees %><br /></p> 
    <p>
  <ul>
 <% User.all.each do |d|%>
         <%= check_box_tag "participant[]", d.id%>
         <%= d.first_name %><br>

 <% end %>
</ul>
</p>
        <%= f.label :Date %>
   <div class="datetime_select">
     <%= select_month Time.now, prefix: :action,
                                field_name: :"action_date(2i)",
                                class: "form-control" %> /
     <%= select_day Time.now, prefix: :action,
                              field_name: :"action_date(3i)",
                              class: "form-control" %> /
     <%= select_year Time.now, prefix: :action,
                               field_name: :"action_date(1i)",
                               start_year: Time.now.year - 1,
                               class: "form-control" %>
   </div><br>
    <%= f.label :action_time %>
   <div class="datetime_select">
   <%= select_hour 12, prefix: :action,
                               field_name: :"action_date(4i)",
                               ampm: true,
                               class: "form-control" %> :
     <%= select_minute 0, prefix: :action,
                                 field_name: :"action_date(5i)",
                                 class: "form-control" %>
    </div>
<br>
   <%= f.submit "Create action", class: "btn btn-primary" %>
 <% end %>
</div>
</div>
</div>
 
<% else %>
<center><h1>Edit action</h1></center><div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="well">
 <%= form_for :event_action, url:action_update_path,method: :put do |f| %>
       <%= f.label :Title %>
   <%= f.text_field :actiontitle, class: "form-control",:disabled=>true%>          <%= f.label :Venu %>
   <%= f.text_field :venue, class: "form-control",:disabled=>true %>      <%= f.label :Description %>
   <%= f.text_area :description, size: "10x3", class: "form-control",:disabled=>true %>
   <%= f.label :Invitees %><br /></p> 
    <p>
  <ul>
 <% @users.each do |role| %>
   <li>
     <%= check_box_tag 'invitee_ids[]', role.id -%>
     <%= role.username -%>
   </li>
 <% end %>
</ul>
</p>
        <%= f.label :Date %>
   <div class="datetime_select">
     <%= select_month Time.now, prefix: :action,
                                field_name: :"action_date(2i)",
                                class: "form-control" %> /
     <%= select_day Time.now, prefix: :action,
                              field_name: :"action_date(3i)",
                              class: "form-control" %> /
     <%= select_year Time.now, prefix: :action,
                               field_name: :"action_date(1i)",
                               start_year: Time.now.year - 1,
                               class: "form-control" %>
   </div><br>
    <%= f.label :action_time %>
   <div class="datetime_select">
   <%= select_hour 12, prefix: :action,
                               field_name: :"action_date(4i)",
                               ampm: true,
                               class: "form-control" %> :
     <%= select_minute 0, prefix: :action,
                                 field_name: :"action_date(5i)",
                                 class: "form-control" %>
    </div>
<br>
   <%= f.submit "Create action", class: "btn btn-primary" %>
 <% end %>
  <% end %>
</div>

</div>
</div>

app/views/actions/index.html.erb
<%= link_to "Create", action_new_path, :remote => true, :data => {:toggle => 'modal', :target => "#myModal"}, class: "btn btn-lg btn-primary"%>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

<div class="container">

<% @actions.each do |e| %>



     
 
<div class="well">
 <strong>Event : </strong><%= link_to e.event_title, '#' %><br>
 <strong>Organiser :</strong><%= %>
<br>

<a href="#" data-toggle="modal" data-target="#myModal-<%= e.id%>">Participents</a><br><br>
<%= link_to 'Edit Event ', "#" ,"class" => "btn btn-primary"  %>
<%= link_to 'Delete Event ', '#' ,"class" => "btn btn-primary"  %>
<div class="status">
<% if e.status==nil %>
<div>
<span class="green-back white-color">open</span>
</div> <%else %>
<div>
<span class="red-back white-color">open</span>
</div>  
<% end %>
</div>    
<div class="container"> <!-- Modal -->
<div class="modal fade" id="myModal-<%= e.id%>" role="dialog">
<div class="modal-dialog">

  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Event : <%= e.event_title  %> </h4>
    </div>
    <div class="modal-body">
   <div class="container">
         <div class="form-group">
<div class="col-md-4">
<% e.users.each do |user|%>
  <%= user.first_name%>
  <% end %>
     
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
 
</div>
</div>
</div>
</div>
</div>
</div></div>
         <% end %>
</div>

app/views/actions/new.js.erb
$("#myModal").html("<%= escape_javascript(render(:partial => 'actions/form'))%>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "", '#', id: "logo" %>
        <nav>
       

          <ul class="nav navbar-nav navbar-right">
            <%= link_to "signup", user_new_path,
                                     class: "btn btn-lg btn-primary" %>
                                     <%= link_to "logout", new_logout_path,method: :delete,
                                 class: "btn btn-lg btn-primary" %>

   <% else %>
     
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>

</body>
</html>

app/views/layouts/common/_flash_message.html.erb
<% if flash.any? %>
<% flash_message = (request.xhr? ? flash.now[ flash.keys.first ] : flash[ flash.keys.first ])
cls_name = "alert-info"
if flash.now[:success] || flash[:success] || flash[:notice]
 cls_name = "alert-success"
 icon_cls_name = "fa-check" 
elsif flash.now[:alert] || flash[:alert]
 cls_name = "alert-warning"
 icon_cls_name = "fa-exclamation-triangle"
elsif flash.now[:error] || flash[:error]
 cls_name = "alert-danger"
 icon_cls_name = "fa-times" 
 %>
 <% end %>

 <% unless flash_message.blank? %>
 <% if flash_message.is_a? String %>
   <div class="<%= request.xhr? ? 'pt-10' : 'pt-20' %>">
   <div class="alert <%= cls_name %> fade in margin-bottom-10" data-alert="alert" id="div_flash_container">
     <a class="close" data-dismiss='alert' href="#">×</a>
     <p><i class="fa <%= icon_cls_name %>"></i> 
       <%= flash_message %></p>
     </div>
   </div>
   <% else %>
 <% flash_message.each do |f| %>
   <div class="<%= request.xhr? ? 'pt-10' : 'pt-20' %>">
   <div class="alert <%= cls_name %> fade in margin-bottom-10" data-alert="alert" id="div_flash_container">
     <a class="close" data-dismiss='alert' href="#">×</a>
     <p><i class="fa <%= icon_cls_name %>"></i> 
       <%= f.to_s.strip %></p>
     </div>
   </div>
   <% end %>
   <% end %>
   <% end %>
   <% end %>

   <script type="text/javascript">
     $(function() {
       $(".alert-success").delay(5000).fadeOut("slow");
       $(".alert-warning, .alert-danger").delay(10000).fadeOut("slow");
     })
   </script>

app/views/static_pages/home.html.erb
<%= render partial: "layouts/common/flash_message", :class => 'alert alert-#{key}' %>
<nav class="navbar navbar-default header">

<div class="container-fluid">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">
   <%= image_tag("download.jpg") %></a>
  </div>
  </div>
<div class="center jumbotron" id="p">
 <h1>Event Scheduling App</h1>
 <h2>
   An event hosting app built for Scheduling Events!!!!
   <a href="http://www.theodinproject.com/"></a>.
 </h2>
   
     <%= link_to "signup", user_new_path,
                                     class: "btn btn-lg btn-primary" %>
   <% else %>
     <%= link_to "login", new_login_path,
                                 class: "btn btn-lg btn-primary" %>
  
</div>

app/views/users/index.html.erb
<table>
<tr>
<th>First_name</th>
<th>Last_name</th>
<th>User_name</th>
<th>Email</th>
<th>phone number</th>
</tr>
<% @user.each do |b|%>
<tr>

<td><%=b.first_name%></td>
<td><%=b.last_name%></td>
<td><%=b.username%></td>
<td><%=b.email%></td>
<td><%=b.phone_number%></td>
</tr>
<%end%>
</table>

app/views/users/new.html.erb
<div class="container">
  <h2></h2>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">signup</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body">
        <div class="container">
          <div class="form-group">
 <div class="col-md-4" id="u">

   <%= form_for :user do |f| %>
   <% if @user.errors.any? %>
    
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

     <%= f.label :first_name  %><br>
     <%= f.text_field :first_name,required: true %><br>

     <%= f.label :last_name%><br>
     <%= f.text_field :last_name,required: true %><br>

     <%= f.label :username %><br>
     <%= f.text_field :username,required: true%><br>
     
     <%= f.label :phone_number %><br>
     <%= f.text_field :phone_number,required: true %><br>
     <%= f.label :email %><br>
     <%= f.text_field :email,required: true %><br>

     <%= f.label :password %><br>
     <%= f.password_field :password,required: true%><br>

     <%= f.label :password_confirmation, "Confirmation" %><br>
     <%= f.password_field :password_confirmation,required: true %><br><br>
    
     <%= f.submit %><br><br>
   <% end %>

 </div>
</div>
</div>
</div>
        </div>
        
      </div>
      
    </div>
  </div>
  